export interface Exercise {
  name: string;
  goal: string;
  equipment: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  intensity: 'Low' | 'Medium' | 'High';
  caption: string;
  description?: string;
  reps?: string;
  duration?: string;
}

export const exercises: Exercise[] = [
  { name: "Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "20 push-ups", description: "Start in plank position, lower chest to floor, push back up. Keep body straight." },
  { name: "Incline Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 incline push-ups", description: "Hands on elevated surface, perform push-ups at an angle. Easier than regular push-ups." },
  { name: "Squats", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "30 squats", description: "Feet shoulder-width apart, lower hips back and down, return to standing. Keep chest up." },
  { name: "Jump Squats", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "High", caption: "20 jump squats", description: "Perform a squat, then explode up into a jump. Land softly and repeat." },
  { name: "Lunges", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "20 lunges each leg", description: "Step forward, lower back knee toward ground, push back to start. Alternate legs." },
  { name: "Glute Bridge", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 glute bridges", description: "Lie on back, knees bent, lift hips up by squeezing glutes. Lower and repeat." },
  { name: "Burpees", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "High", caption: "15 burpees", description: "Squat down, jump back to plank, do push-up, jump feet to hands, jump up with arms overhead." },
  { name: "Mountain Climbers", goal: "HIIT", equipment: "Bodyweight", difficulty: "Medium", intensity: "High", caption: "1 min mountain climbers", description: "Start in plank, alternate bringing knees to chest rapidly. Keep hips level." },
  { name: "Plank", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "1 min plank", description: "Hold push-up position on forearms. Keep body straight from head to heels." },
  { name: "Side Plank", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "30 sec per side", description: "Lie on side, prop up on forearm, lift hips. Keep body straight. Switch sides." },
  { name: "Bicycle Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "20 bicycle crunches", description: "Lie on back, hands behind head, alternate bringing opposite elbow to knee." },
  { name: "Russian Twists", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "20 twists", description: "Sit with knees bent, lean back slightly, rotate torso side to side holding weight." },
  { name: "Jumping Jacks", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "High", caption: "100 jumping jacks", description: "Jump feet apart while raising arms overhead, jump back to start. Keep rhythm steady." },
  { name: "High Knees", goal: "HIIT", equipment: "Bodyweight", difficulty: "Medium", intensity: "High", caption: "30 sec high knees", description: "Run in place bringing knees up to waist level. Pump arms for momentum." },
  { name: "Tricep Dips", goal: "Strength", equipment: "Chair", difficulty: "Medium", intensity: "Medium", caption: "15 tricep dips", description: "Sit on chair edge, hands beside hips, lower body by bending arms, push back up." },
  { name: "Dumbbell Curl", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 curls each arm", description: "Hold weights at sides, curl up to shoulders, lower slowly. Keep elbows still." },
  { name: "Shoulder Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 presses", description: "Hold weights at shoulder level, press straight up overhead, lower back down." },
  { name: "Deadlift", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 deadlifts", description: "Hold weights in front, hinge at hips, lower weights toward floor, stand back up." },
  { name: "Chest Fly", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 chest flys", description: "Lie on back, arms wide with weights, bring arms together over chest, lower back out." },
  { name: "Side Lunges", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 side lunges each leg", description: "Step wide to one side, bend that knee, push back to center. Alternate sides." },
  { name: "Wall Sit", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "🪑 1 min wall sit", description: "Back against wall, slide down to sitting position, hold. Thighs parallel to floor." },
  { name: "Burpee to Push-Up", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 burpee push-ups", description: "Regular burpee but add a push-up when in plank position. More challenging variation." },
  { name: "Jump Rope", goal: "HIIT", equipment: "Rope", difficulty: "Medium", intensity: "High", caption: "2 min jump rope", description: "Jump over rope as it passes under feet. Keep light on toes, steady rhythm." },
  { name: "Box Jumps", goal: "HIIT", equipment: "Box", difficulty: "Hard", intensity: "High", caption: "15 box jumps", description: "Jump onto sturdy box or platform, step down carefully. Land softly with bent knees." },
  { name: "Kettlebell Swing", goal: "Full Body", equipment: "Kettlebell", difficulty: "Medium", intensity: "Medium", caption: "20 swings", description: "Hinge at hips, swing kettlebell between legs, drive hips forward to chest level." },
  { name: "Hip Thrust", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 hip thrusts", description: "Shoulders on bench, feet on floor, drive hips up by squeezing glutes." },
  { name: "Side Leg Raises", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "20 per side", description: "Lie on side, lift top leg up and down. Keep body straight, control the movement." },
  { name: "Flutter Kicks", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "30 sec flutter kicks", description: "Lie on back, legs straight, alternate small kicks up and down. Keep lower back pressed down." },
  { name: "Wall Handstand Hold", goal: "Strength", equipment: "Wall", difficulty: "Hard", intensity: "Medium", caption: "‍️ 30 sec handstand hold", description: "Kick up to handstand against wall, hold position. Keep arms straight and strong." },
  { name: "Step-Ups", goal: "HIIT", equipment: "Bench", difficulty: "Medium", intensity: "High", caption: "20 step-ups each leg", description: "Step up onto bench with one foot, bring other foot up, step back down. Alternate." },
  { name: "Reverse Lunges", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 per leg", description: "Step backward into lunge, lower back knee toward ground, return to start." },
  { name: "Pike Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 pike push-ups", description: "Start in downward dog position, lower head toward hands, push back up." },
  { name: "Tuck Jumps", goal: "HIIT", equipment: "Bodyweight", difficulty: "Hard", intensity: "High", caption: "15 tuck jumps", description: "Jump up bringing knees to chest, land softly. Explosive movement." },
  { name: "Superman Hold", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "‍️ 30 sec hold", description: "Lie face down, lift chest and legs off ground simultaneously. Hold position." },
  { name: "Side Plank Hip Dips", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 dips per side", description: "Hold side plank, lower hip toward ground, lift back up. Control the movement." },
  { name: "Wall Walks", goal: "Full Body", equipment: "Wall", difficulty: "Hard", intensity: "Medium", caption: "5 wall walks", description: "Start in plank facing away from wall, walk feet up wall while walking hands closer." },
  { name: "Calf Raises", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "30 calf raises", description: "Rise up on toes, hold briefly, lower slowly. Can be done on step for more range." },
  { name: "Dumbbell Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 rows per arm", description: "Bend over, pull dumbbell to hip, lower slowly. Keep back straight throughout." },
  { name: "Jump Lunges", goal: "HIIT", equipment: "Bodyweight", difficulty: "Hard", intensity: "High", caption: "10 per leg", description: "Lunge position, jump and switch legs in air, land in opposite lunge." },
  { name: "Plank Shoulder Taps", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "20 taps each shoulder", description: "Hold plank position, tap opposite shoulder with hand. Keep hips stable." },
  { name: "Box Burpee", goal: "Full Body", equipment: "Box", difficulty: "Hard", intensity: "Medium", caption: "10 burpees on box", description: "Perform burpee with hands on box instead of floor. Step or jump down carefully." },
  { name: "Glute Kickbacks", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 kickbacks per leg", description: "On hands and knees, kick one leg back and up. Squeeze glute at top." },
  
  // Additional Bodyweight Exercises
  { name: "Bear Crawl", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "30 sec bear crawl", description: "Crawl forward on hands and feet, knees just off ground. Keep core tight." },
  { name: "Crab Walk", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "20 steps crab walk", description: "Sit with hands behind you, lift hips, walk on hands and feet. Face up." },
  { name: "Frog Jumps", goal: "HIIT", equipment: "Bodyweight", difficulty: "Hard", intensity: "High", caption: "15 frog jumps", description: "Squat down, jump forward explosively, land in squat. Like a frog hopping." },
  { name: "Star Jumps", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "High", caption: "20 star jumps", description: "Jump spreading arms and legs wide like a star, return to start position." },
  { name: "Squat Pulses", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "20 squat pulses", description: "Hold bottom of squat, pulse up and down in small movements. Stay low." },
  { name: "Lunge Pulses", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 lunge pulses each leg", description: "Hold bottom of lunge, pulse up and down. Keep front knee over ankle." },
  { name: "Single Leg Glute Bridge", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 single leg bridges each", description: "Bridge with one leg extended. Lift hips using single glute. Very challenging." },
  { name: "Donkey Kicks", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 donkey kicks each leg", description: "On hands and knees, kick one leg up behind you. Keep knee bent at 90 degrees." },
  { name: "Fire Hydrants", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 fire hydrants each leg", description: "On hands and knees, lift leg out to side like dog at fire hydrant. Keep hips level." },
  { name: "Dead Bug", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "10 dead bugs each side", description: "Lie on back, arms up, knees bent. Lower opposite arm and leg, return to start." },
  { name: "Bird Dog", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "10 bird dogs each side", description: "On hands and knees, extend opposite arm and leg, hold, return to start." },
  { name: "Hollow Body Hold", goal: "Abs", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "30 sec hollow hold", description: "Lie on back, press lower back down, lift shoulders and legs. Hold hollow shape." },
  { name: "V-Ups", goal: "Abs", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "15 v-ups", description: "Lie flat, simultaneously lift legs and torso to form V shape. Touch toes if possible." },
  { name: "Leg Raises", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 leg raises", description: "Lie on back, lift straight legs to 90 degrees, lower slowly without touching floor." },
  { name: "Reverse Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 reverse crunches", description: "Lie on back, bring knees to chest by lifting hips off ground. Control the movement." },
  { name: "Plank Up-Downs", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 plank up-downs", description: "Start in plank, go down to forearms one arm at a time, return to hands." },
  { name: "Plank Jacks", goal: "HIIT", equipment: "Bodyweight", difficulty: "Hard", intensity: "High", caption: "20 plank jacks", description: "Hold plank position, jump feet apart and together like jumping jacks." },
  { name: "Commando Crawl", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 steps commando crawl", description: "Army crawl forward using elbows and knees. Stay low to ground." },
  { name: "Inch Worms", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "10 inch worms", description: "Stand, walk hands out to plank, walk feet to hands. Like measuring with inches." },
  { name: "Skater Hops", goal: "HIIT", equipment: "Bodyweight", difficulty: "Medium", intensity: "High", caption: "️ 20 skater hops", description: "Hop side to side on one foot, like speed skating. Keep low and controlled." },
  { name: "Lateral Bounds", goal: "HIIT", equipment: "Bodyweight", difficulty: "Hard", intensity: "High", caption: "️ 10 lateral bounds each side", description: "Explosive side-to-side jumps, land on one foot, push off to other side." },
  { name: "Single Leg Deadlift", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "8 single leg deadlifts each", description: "Balance on one leg, hinge at hip, reach toward ground. Stand back up." },
  { name: "Pistol Squats", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "5 pistol squats each leg", description: "Single leg squat with other leg extended forward. Very challenging balance and strength move." },
  { name: "Archer Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "5 archer push-ups each side", description: "Wide hand position, shift weight to one arm during push-up. Very advanced." },
  { name: "Diamond Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 diamond push-ups", description: "Hands form diamond shape under chest. Targets triceps more than regular push-ups." },
  { name: "Wide Grip Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "12 wide grip push-ups", description: "Hands wider than shoulders. Targets chest more than regular push-ups." },
  { name: "Decline Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 decline push-ups", description: "Feet elevated on bench or step. More challenging than regular push-ups." },
  { name: "Hindu Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "️ 8 hindu push-ups", description: "Flow from downward dog to cobra pose. Continuous fluid movement." },
  { name: "Dive Bomber Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "️ 8 dive bomber push-ups", description: "Similar to Hindu push-ups but return to start position. Like diving motion." },
  { name: "Spiderman Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "️ 10 spiderman push-ups", description: "During push-up, bring knee to elbow. Alternate sides each rep." },
  { name: "T Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "8 T push-ups", description: "After push-up, rotate to side plank with arm reaching up. Form T shape." },
  { name: "Clap Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "5 clap push-ups", description: "Explosive push-up with hands leaving ground to clap. Land softly." },
  { name: "Single Arm Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "3 single arm push-ups each", description: "Push-up using only one arm. Extremely advanced movement." },
  { name: "Handstand Push-Ups", goal: "Strength", equipment: "Wall", difficulty: "Hard", intensity: "Medium", caption: "5 handstand push-ups", description: "Inverted push-up against wall. Lower head toward ground, press back up." },
  { name: "Wall Sit Pulses", goal: "Strength", equipment: "Wall", difficulty: "Medium", intensity: "Medium", caption: "20 wall sit pulses", description: "Hold wall sit position, pulse up and down in small movements." },
  { name: "Wall Angels", goal: "Strength", equipment: "Wall", difficulty: "Easy", intensity: "Medium", caption: "15 wall angels", description: "Back against wall, move arms up and down like making snow angel." },
  { name: "Heel Flicks", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "High", caption: "30 sec heel flicks", description: "Run in place kicking heels up to touch glutes. Quick, light steps." },
  { name: "Arm Circles", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "20 arm circles each direction", description: "Extend arms out, make small then large circles. Warm-up movement." },
  { name: "Leg Swings", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "15 leg swings each leg", description: "Hold wall for balance, swing leg forward and back. Dynamic stretching." },
  { name: "Hip Circles", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "10 hip circles each direction", description: "Hands on hips, make large circles with hips. Mobility exercise." },
  { name: "Ankle Rolls", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "10 ankle rolls each foot", description: "Lift foot, rotate ankle in circles. Helps with mobility and warm-up." },
  { name: "Neck Rolls", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "5 neck rolls each direction", description: "Gently roll head in circles. Be slow and controlled to avoid injury." },
  { name: "Shoulder Shrugs", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 shoulder shrugs", description: "Lift shoulders toward ears, hold briefly, lower slowly. Can add weight." },
  { name: "Torso Twists", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "️ 20 torso twists", description: "Stand with arms crossed, rotate torso side to side. Keep hips facing forward." },
  { name: "Standing Knee Raises", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 knee raises each leg", description: "Stand tall, lift knee toward chest. Alternate legs or single leg sets." },
  { name: "Standing Oblique Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 oblique crunches each side", description: "Stand, bring elbow toward lifted knee on same side. Targets side abs." },
  { name: "Marching in Place", goal: "HIIT", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec marching", description: "Lift knees up while marching in place. Good warm-up or active recovery." },
  { name: "Toe Touches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "15 toe touches", description: "Lie on back, reach toward toes with straight legs. Crunch up to touch." },
  { name: "Heel Touches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "20 heel touches", description: "Lie on back, reach toward heels by crunching to side. Alternate sides." },
  { name: "Cross Body Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "15 cross body crunches each side", description: "Lie on back, bring opposite elbow toward knee. Targets obliques." },
  { name: "Sit-Ups", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "20 sit-ups", description: "Lie on back, sit all the way up to knees. Full range of motion." },
  { name: "Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "25 crunches", description: "Lie on back, lift shoulders off ground. Smaller movement than sit-ups." },
  { name: "Reverse Plank", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "30 sec reverse plank", description: "Sit with legs extended, lift hips up. Support weight on hands behind you." },
  { name: "Side Plank Rotations", goal: "Abs", equipment: "Bodyweight", difficulty: "Hard", intensity: "Medium", caption: "10 side plank rotations each side", description: "Hold side plank, rotate top arm under body and back up." },
  { name: "Plank to Downward Dog", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", intensity: "Medium", caption: "10 plank to downward dog", description: "Start in plank, push hips up to downward dog, return to plank." },
  { name: "Downward Dog", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Medium", caption: "30 sec downward dog", description: "Hands and feet on ground, hips up high. Form inverted V shape." },
  { name: "Cobra Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec cobra stretch", description: "Lie face down, push chest up with arms. Stretch front of body." },
  { name: "Child's Pose", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec child's pose", description: "Kneel, sit back on heels, reach arms forward. Restful yoga position." },
  { name: "Cat Cow Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "10 cat cow stretches", description: "On hands and knees, arch and round back alternately. Spinal mobility." },
  { name: "Thread the Needle", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "🪡 10 thread the needle each side", description: "Side plank, thread top arm under body. Thoracic spine mobility." },
  { name: "World's Greatest Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", intensity: "Low", caption: "5 world's greatest stretch each side", description: "Lunge with rotation and reach. Hits multiple muscle groups." },
  { name: "90/90 Hip Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec 90/90 hip stretch", description: "Sit with both legs at 90 degrees. Stretch hips in different directions." },
  { name: "Pigeon Pose", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec pigeon pose each side", description: "One leg forward bent, other leg back straight. Deep hip stretch." },
  { name: "Figure 4 Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec figure 4 stretch each side", description: "Ankle on opposite knee, pull thigh toward chest. Hip and glute stretch." },
  { name: "Seated Spinal Twist", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "️ 30 sec spinal twist each side", description: "Sit cross-legged, rotate spine to one side. Hold and switch." },
  { name: "Seated Forward Fold", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec forward fold", description: "Sit with legs extended, fold forward over legs. Hamstring stretch." },
  { name: "Standing Forward Fold", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec standing forward fold", description: "Stand, fold forward at hips, let arms hang. Hamstring and back stretch." },
  { name: "Standing Quad Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec quad stretch each leg", description: "Pull heel toward glute while standing. Hold wall for balance." },
  { name: "Standing Calf Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec calf stretch each leg", description: "Step back, keep heel down, lean forward. Stretch back leg calf." },
  { name: "Standing Hamstring Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec hamstring stretch each leg", description: "Heel on step, lean forward over straight leg. Stretch back of thigh." },
  { name: "Arm Crossovers", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "15 arm crossovers", description: "Swing arms across body and back. Dynamic shoulder warm-up." },
  { name: "Tricep Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec tricep stretch each arm", description: "Pull elbow behind head with opposite hand. Stretch back of arm." },
  { name: "Shoulder Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec shoulder stretch each arm", description: "Pull arm across body with opposite hand. Stretch shoulder and back." },
  { name: "Chest Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec chest stretch", description: "Arm against wall, turn body away. Stretch front of shoulder and chest." },
  { name: "Hip Flexor Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec hip flexor stretch each leg", description: "Lunge position, push hips forward. Stretch front of hip." },
  { name: "IT Band Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec IT band stretch each leg", description: "Cross legs, lean to one side. Stretch outside of thigh." },
  { name: "Glute Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", intensity: "Low", caption: "30 sec glute stretch each leg", description: "Ankle on knee, pull thigh to chest. Stretch glute muscles." },
  
  // Dumbbell Exercises
  { name: "Dumbbell Squat", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "️ 15 dumbbell squats", description: "Hold dumbbells at sides or shoulders, perform squats with added weight." },
  { name: "Goblet Squat", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 goblet squats", description: "Hold one dumbbell at chest like a goblet, squat down keeping chest up." },
  { name: "Dumbbell Lunge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 dumbbell lunges each leg", description: "Hold dumbbells at sides, step forward into lunge, return to start." },
  { name: "Dumbbell Step-Ups", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 dumbbell step-ups each leg" },
  { name: "Dumbbell Romanian Deadlift", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 Romanian deadlifts" },
  { name: "Dumbbell Sumo Deadlift", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 sumo deadlifts" },
  { name: "Dumbbell Bench Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 dumbbell bench press" },
  { name: "Dumbbell Incline Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "10 incline press" },
  { name: "Dumbbell Decline Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "10 decline press" },
  { name: "Dumbbell Flyes", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 dumbbell flyes" },
  { name: "Dumbbell Pullover", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 dumbbell pullovers" },
  { name: "Bent Over Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 bent over rows" },
  { name: "Single Arm Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 single arm rows each" },
  { name: "Upright Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 upright rows" },
  { name: "Reverse Fly", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 reverse flyes" },
  { name: "Lateral Raise", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "️ 15 lateral raises" },
  { name: "Front Raise", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 front raises" },
  { name: "Rear Delt Fly", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 rear delt flyes" },
  { name: "Arnold Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 Arnold presses", description: "Start with palms facing you, rotate to palms forward as you press overhead. Named after Arnold Schwarzenegger." },
  { name: "21s Bicep Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "21s bicep curls", description: "7 bottom-half curls, 7 top-half curls, 7 full curls. Total of 21 reps without rest." },
  { name: "Man Makers", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "5 man makers", description: "Burpee with dumbbells, add renegade row in plank, then squat to overhead press." },
  { name: "Push Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 push presses" },
  { name: "Dumbbell Snatch", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "8 dumbbell snatches each arm" },
  { name: "Dumbbell Clean", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "8 dumbbell cleans each arm" },
  { name: "Dumbbell Thruster", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 dumbbell thrusters" },

  { name: "Dumbbell Burpee", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "8 dumbbell burpees" },
  { name: "Renegade Rows", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 renegade rows" },
  { name: "Dumbbell Mountain Climbers", goal: "HIIT", equipment: "Dumbbells", difficulty: "Hard", intensity: "High", caption: "️ 20 dumbbell mountain climbers", description: "Plank position with hands on dumbbells, alternate bringing knees to chest." },
  { name: "Bicep Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 bicep curls", description: "Hold dumbbells at sides, curl up to shoulders, lower slowly. Keep elbows still." },
  { name: "Hammer Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 hammer curls", description: "Hold dumbbells with neutral grip (thumbs up), curl up like holding hammers." },
  { name: "Concentration Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 concentration curls each arm" },


  { name: "Overhead Tricep Extension", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 overhead tricep extensions" },
  { name: "Lying Tricep Extension", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 lying tricep extensions" },
  { name: "Tricep Kickbacks", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 tricep kickbacks" },
  { name: "Close Grip Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 close grip press" },
  { name: "Dumbbell Shrugs", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", intensity: "Medium", caption: "15 dumbbell shrugs" },
  { name: "Farmer's Walk", goal: "Full Body", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "30 sec farmer's walk" },
  { name: "Suitcase Carry", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "20 steps suitcase carry each side" },
  { name: "Overhead Carry", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "20 steps overhead carry" },
  { name: "Dumbbell Swing", goal: "HIIT", equipment: "Dumbbells", difficulty: "Medium", intensity: "High", caption: "20 dumbbell swings", description: "Like kettlebell swing but with dumbbell. Hinge at hips, swing to chest level." },
  { name: "Single Arm Swing", goal: "HIIT", equipment: "Dumbbells", difficulty: "Medium", intensity: "High", caption: "15 single arm swings each", description: "One-handed dumbbell swing. Alternate arms or complete all reps on one side." },
  { name: "Dumbbell High Pull", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 dumbbell high pulls" },
  { name: "Dumbbell Windmill", goal: "Abs", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "️ 8 windmills each side" },
  { name: "Turkish Get-Up", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "3 Turkish get-ups each side", description: "Complex movement from lying to standing while holding weight overhead. Practice without weight first." },
  { name: "Dumbbell Crawl", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 steps dumbbell crawl" },
  { name: "Weighted Sit-Ups", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "15 weighted sit-ups" },
  { name: "Weighted Crunches", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "20 weighted crunches" },
  { name: "Weighted Russian Twists", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "20 weighted Russian twists" },
  { name: "Weighted Plank", goal: "Abs", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "30 sec weighted plank" },
  { name: "Weighted Glute Bridge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "15 weighted glute bridges" },
  { name: "Single Leg Hip Thrust", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 single leg hip thrusts each" },
  { name: "Weighted Hip Thrust", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "15 weighted hip thrusts" },
  { name: "Bulgarian Split Squat", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 Bulgarian split squats each leg" },
  { name: "Reverse Lunge to Knee Drive", goal: "HIIT", equipment: "Dumbbells", difficulty: "Medium", intensity: "High", caption: "12 reverse lunge to knee drive each leg", description: "Reverse lunge, then drive back knee up to chest. Explosive movement." },
  { name: "Lateral Lunge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "️ 12 lateral lunges each leg" },
  { name: "Curtsy Lunge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "12 curtsy lunges each leg" },
  { name: "Walking Lunge", goal: "HIIT", equipment: "Dumbbells", difficulty: "Medium", intensity: "High", caption: "20 walking lunges", description: "Lunge forward, bring back foot to meet front, lunge with other leg." },
  { name: "Reverse Fly to External Rotation", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "10 reverse fly to external rotation" },
  { name: "Dumbbell Complex", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", intensity: "Medium", caption: "5 dumbbell complexes" },
  { name: "Dumbbell Ladder", goal: "HIIT", equipment: "Dumbbells", difficulty: "Hard", intensity: "High", caption: "1-10 dumbbell ladder", description: "Perform 1 rep, then 2, then 3, up to 10 reps of chosen dumbbell exercise." },
  { name: "Dumbbell Tabata", goal: "HIIT", equipment: "Dumbbells", difficulty: "Hard", intensity: "High", caption: "4 min dumbbell tabata", description: "20 seconds max effort, 10 seconds rest, repeat 8 rounds with dumbbells." },
  { name: "Dumbbell EMOM", goal: "HIIT", equipment: "Dumbbells", difficulty: "Hard", intensity: "High", caption: "5 min dumbbell EMOM", description: "Every Minute On the Minute - perform set reps, rest remainder of minute." },
  { name: "Dumbbell Circuit", goal: "Full Body", equipment: "Dumbbells", difficulty: "Medium", intensity: "Medium", caption: "3 rounds dumbbell circuit" },
  
  // Full Gym Exercises
  { name: "Barbell Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "️ 12 barbell squats", description: "Barbell on upper back, squat down until thighs parallel, stand back up." },
  { name: "Front Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "️ 10 front squats" },
  { name: "Overhead Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "8 overhead squats" },
  { name: "Barbell Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 barbell deadlifts", description: "Lift barbell from floor by standing up, hinge at hips, keep back straight." },
  { name: "Sumo Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 sumo deadlifts" },
  { name: "Romanian Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 Romanian deadlifts" },
  { name: "Stiff Leg Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 stiff leg deadlifts" },
  { name: "Barbell Row", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 barbell rows" },
  { name: "Dead Stop Barbell Row", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "10 dead stop barbell rows", description: "Row barbell from floor to chest, pause on floor between reps. No momentum." },
  { name: "T-Bar Row", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 T-bar rows" },
  { name: "Barbell Bench Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 barbell bench press", description: "Lie on bench, lower barbell to chest, press back up. Keep feet on floor." },
  { name: "Incline Barbell Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 incline barbell press" },
  { name: "Decline Barbell Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 decline barbell press" },
  { name: "Overhead Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 overhead press" },
  { name: "Push Press", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "8 push press" },
  { name: "Push Jerk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 push jerks" },
  { name: "Split Jerk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 split jerks" },
  { name: "Clean and Jerk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "5 clean and jerks" },
  { name: "Power Clean", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 power cleans" },
  { name: "Hang Clean", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 hang cleans" },
  { name: "Snatch", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "5 snatches" },
  { name: "Power Snatch", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 power snatches" },
  { name: "Hang Snatch", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 hang snatches" },
  { name: "Thruster", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "10 thrusters" },
  { name: "Barbell Curl", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 barbell curls" },
  { name: "Close Grip Bench Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 close grip bench press" },
  { name: "Skull Crushers", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 skull crushers", description: "Lie on bench, lower barbell toward forehead by bending elbows, extend back up. Also called lying tricep extensions." },
  { name: "Barbell Shrugs", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 barbell shrugs" },
  { name: "Upright Row", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 upright rows" },
  { name: "Face Pulls", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 face pulls" },
  { name: "Cable Crossover", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 cable crossovers" },
  { name: "Cable Fly", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 cable flyes" },
  { name: "Lat Pulldown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "⬇️ 12 lat pulldowns" },
  { name: "Wide Grip Pulldown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "️ 12 wide grip pulldowns" },
  { name: "Close Grip Pulldown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 close grip pulldowns" },
  { name: "Seated Cable Row", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 seated cable rows" },
  { name: "Cable Bicep Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 cable bicep curls" },
  { name: "Cable Hammer Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 cable hammer curls" },
  { name: "Cable Tricep Pushdown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "⬇️ 15 cable tricep pushdowns" },
  { name: "Overhead Cable Extension", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 overhead cable extensions" },
  { name: "Cable Lateral Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "️ 15 cable lateral raises" },
  { name: "Cable Rear Delt Fly", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 cable rear delt flyes" },
  { name: "Cable Wood Chops", goal: "Abs", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "🪓 12 cable wood chops each side" },
  { name: "Cable Russian Twists", goal: "Abs", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 cable Russian twists" },
  { name: "Cable Crunches", goal: "Abs", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "15 cable crunches" },
  { name: "Hanging Knee Raises", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "12 hanging knee raises" },
  { name: "Hanging Leg Raises", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "10 hanging leg raises" },
  { name: "Toes to Bar", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "8 toes to bar" },
  { name: "L-Sit", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 sec L-sit" },
  { name: "Pull-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "8 pull-ups", description: "Hang from bar, pull body up until chin over bar, lower with control." },
  { name: "Chin-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "8 chin-ups" },
  { name: "Wide Grip Pull-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "️ 6 wide grip pull-ups" },
  { name: "Commando Pull-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "5 commando pull-ups" },
  { name: "Muscle-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "3 muscle-ups" },
  { name: "Dips", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "⬇️ 10 dips" },
  { name: "Weighted Dips", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "⬇️ 8 weighted dips" },
  { name: "Ring Dips", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "6 ring dips" },
  { name: "Ring Push-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "8 ring push-ups" },
  { name: "Ring Rows", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 ring rows" },
  { name: "Ring Muscle-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "2 ring muscle-ups" },
  { name: "Leg Press", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 leg press" },
  { name: "Hack Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "️ 12 hack squats" },
  { name: "Leg Extension", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 leg extensions" },
  { name: "Leg Curl", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 leg curls" },
  { name: "Calf Press", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "20 calf press" },
  { name: "Standing Calf Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "20 standing calf raises" },
  { name: "Seated Calf Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "20 seated calf raises" },
  { name: "Hip Abduction", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 hip abductions" },
  { name: "Hip Adduction", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "15 hip adductions" },
  { name: "Chest Press Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 chest press machine" },
  { name: "Shoulder Press Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "️ 12 shoulder press machine" },
  { name: "Lat Pulldown Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "⬇️ 12 lat pulldown machine" },
  { name: "Row Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 row machine" },
  { name: "Pec Deck", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 pec deck" },
  { name: "Reverse Pec Deck", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 reverse pec deck" },
  { name: "Preacher Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 preacher curls" },
  { name: "Cable Preacher Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "12 cable preacher curls" },
  { name: "Smith Machine Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "️ 12 Smith machine squats" },
  { name: "Smith Machine Bench", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "10 Smith machine bench" },
  { name: "Smith Machine Row", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "12 Smith machine rows" },
  { name: "Smith Machine Calf Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "20 Smith machine calf raises" },
  { name: "Treadmill Sprint", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "High", caption: "30 sec treadmill sprint", description: "Run at maximum speed on treadmill for 30 seconds. High intensity interval." },
  { name: "Treadmill Incline Walk", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "Low", caption: "2 min incline walk", description: "Walk on steep incline (10-15%). Good for active recovery or warm-up." },
  { name: "Stationary Bike", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "Low", caption: "2 min stationary bike", description: "Cycle at moderate to high intensity. Adjust resistance as needed." },
  { name: "Elliptical", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "Low", caption: "2 min elliptical", description: "Full body cardio machine. Use arms and legs together for best results." },
  { name: "Rowing Machine", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "500m rowing machine", description: "Pull with legs first, then back, then arms. Push with legs to return." },
  { name: "Stair Climber", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "2 min stair climber", description: "Step up continuously on moving stairs. Keep good posture, don't lean." },
  { name: "Battle Ropes", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "High", caption: "🪢 30 sec battle ropes", description: "Alternate waves, spirals, or slams with heavy ropes. Full body workout." },
  { name: "Tire Flips", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "10 tire flips" },
  { name: "Sledgehammer Swings", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 sledgehammer swings" },
  { name: "Prowler Push", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yard prowler push" },
  { name: "Sled Pull", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yard sled pull" },
  { name: "Atlas Stone Lift", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "5 atlas stone lifts" },
  { name: "Sandbag Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "30 sec sandbag carry" },
  { name: "Medicine Ball Slam", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "15 medicine ball slams" },
  { name: "Medicine Ball Throw", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "10 medicine ball throws" },
  { name: "Wall Ball", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "15 wall balls" },
  { name: "Box Step-Ups", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "High", caption: "20 box step-ups" },
  { name: "Box Jump Overs", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "10 box jump overs" },
  { name: "Lateral Box Jumps", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "10 lateral box jumps each side" },
  { name: "Depth Jumps", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "8 depth jumps" },
  { name: "Broad Jumps", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "️ 10 broad jumps" },
  { name: "Vertical Jumps", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "15 vertical jumps" },
  { name: "Single Leg Box Jumps", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "5 single leg box jumps each" },
  { name: "Agility Ladder", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "30 sec agility ladder" },
  { name: "Cone Drills", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "30 sec cone drills" },
  { name: "Shuttle Runs", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "5 shuttle runs" },
  { name: "Sprint Intervals", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "High", caption: "8x20 yard sprints" },
  { name: "Parachute Runs", goal: "HIIT", equipment: "Full Gym", difficulty: "Hard", intensity: "High", caption: "30 sec parachute runs" },
  { name: "Resistance Band Runs", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "30 sec resistance band runs" },
  { name: "Bounding", goal: "HIIT", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 bounds" },
  { name: "High Skips", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "30 sec high skips" },

  { name: "Backpedal", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "20 yards backpedal" },
  { name: "Side Shuffle", goal: "HIIT", equipment: "Full Gym", difficulty: "Easy", intensity: "Medium", caption: "️ 20 yards side shuffle each direction" },
  { name: "Bear Crawl Forward", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards bear crawl forward" },
  { name: "Bear Crawl Backward", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards bear crawl backward" },
  { name: "Crab Walk Forward", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards crab walk forward" },
  { name: "Crab Walk Backward", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards crab walk backward" },
  { name: "Duck Walk", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards duck walk" },
  { name: "Lizard Crawl", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards lizard crawl" },
  { name: "Army Crawl", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards army crawl" },
  { name: "Spiderman Crawl", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "️ 20 yards spiderman crawl" },
  { name: "Gorilla Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards gorilla walk" },
  { name: "Frog Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards frog walk" },
  { name: "Seal Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards seal walk" },
  { name: "Inchworm Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards inchworm walk" },
  { name: "Wheelbarrow Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards wheelbarrow walk" },
  { name: "Partner Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards partner carry" },
  { name: "Fireman Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards fireman carry", description: "Carry partner over shoulders, supporting with both arms. Switch roles." },
  { name: "Piggyback Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards piggyback carry" },
  { name: "Overhead Plate Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards overhead plate carry" },
  { name: "Front Loaded Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards front loaded carry" },
  { name: "Front Rack Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards front rack carry", description: "Hold barbell in crook of elbows, walk forward maintaining upright posture." },
  { name: "Yoke Walk", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards yoke walk" },
  { name: "Frame Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "️ 20 yards frame carry" },
  { name: "Log Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards log carry" },
  { name: "Keg Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards keg carry" },
  { name: "Stone Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards stone carry" },
  { name: "Bucket Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards bucket carry" },
  { name: "Water Jug Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", intensity: "Medium", caption: "20 yards water jug carry" },
  { name: "Odd Object Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", intensity: "Medium", caption: "20 yards odd object carry" }
];

export const fitnessGoals = ["Abs", "Strength", "HIIT", "Full Body"];
export const timeOptions = ["5", "10", "15", "20", "25", "30"];
export const equipmentOptions = ["Bodyweight", "Dumbbells", "Full Gym"];