export interface Exercise {
  name: string;
  goal: string;
  equipment: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  caption: string;
  reps?: string;
  duration?: string;
}

export const exercises: Exercise[] = [
  { name: "Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "20 push-ups" },
  { name: "Incline Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "15 incline push-ups" },
  { name: "Squats", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "️ 30 squats" },
  { name: "Jump Squats", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "20 jump squats" },
  { name: "Lunges", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "20 lunges each leg" },
  { name: "Glute Bridge", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "15 glute bridges" },
  { name: "Burpees", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "15 burpees" },
  { name: "Mountain Climbers", goal: "Cardio", equipment: "Bodyweight", difficulty: "Medium", caption: "️ 1 min mountain climbers" },
  { name: "Plank", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "1 min plank" },
  { name: "Side Plank", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "30 sec per side" },
  { name: "Bicycle Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "20 bicycle crunches" },
  { name: "Russian Twists", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", caption: "20 twists" },
  { name: "Jumping Jacks", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "100 jumping jacks" },
  { name: "High Knees", goal: "Cardio", equipment: "Bodyweight", difficulty: "Medium", caption: "30 sec high knees" },
  { name: "Tricep Dips", goal: "Strength", equipment: "Chair", difficulty: "Medium", caption: "15 tricep dips" },
  { name: "Dumbbell Curl", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 curls each arm" },
  { name: "Shoulder Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "️ 12 presses" },
  { name: "Deadlift", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "10 deadlifts" },
  { name: "Chest Fly", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 chest flys" },
  { name: "Side Lunges", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "15 side lunges each leg" },
  { name: "Wall Sit", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "🪑 1 min wall sit" },
  { name: "Burpee to Push-Up", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "10 burpee push-ups" },
  { name: "Jump Rope", goal: "Cardio", equipment: "Rope", difficulty: "Medium", caption: "2 min jump rope" },
  { name: "Box Jumps", goal: "Cardio", equipment: "Box", difficulty: "Hard", caption: "15 box jumps" },
  { name: "Kettlebell Swing", goal: "Full Body", equipment: "Kettlebell", difficulty: "Medium", caption: "20 swings" },
  { name: "Hip Thrust", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "15 hip thrusts" },
  { name: "Side Leg Raises", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "20 per side" },
  { name: "Flutter Kicks", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "30 sec flutter kicks" },
  { name: "Wall Handstand Hold", goal: "Strength", equipment: "Wall", difficulty: "Hard", caption: "️ 30 sec handstand hold" },
  { name: "Step-Ups", goal: "Cardio", equipment: "Bench", difficulty: "Medium", caption: "20 step-ups each leg" },
  { name: "Reverse Lunges", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "15 per leg" },
  { name: "Pike Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "10 pike push-ups" },
  { name: "Tuck Jumps", goal: "Cardio", equipment: "Bodyweight", difficulty: "Hard", caption: "15 tuck jumps" },
  { name: "Superman Hold", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "️ 30 sec hold" },
  { name: "Side Plank Hip Dips", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "15 dips per side" },
  { name: "Wall Walks", goal: "Full Body", equipment: "Wall", difficulty: "Hard", caption: "5 wall walks" },
  { name: "Calf Raises", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "30 calf raises" },
  { name: "Dumbbell Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 rows per arm" },
  { name: "Jump Lunges", goal: "Cardio", equipment: "Bodyweight", difficulty: "Hard", caption: "10 per leg" },
  { name: "Plank Shoulder Taps", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "20 taps each shoulder" },
  { name: "Box Burpee", goal: "Full Body", equipment: "Box", difficulty: "Hard", caption: "10 burpees on box" },
  { name: "Glute Kickbacks", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "15 kickbacks per leg" },
  
  // Additional Bodyweight Exercises
  { name: "Bear Crawl", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", caption: "30 sec bear crawl" },
  { name: "Crab Walk", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", caption: "20 steps crab walk" },
  { name: "Frog Jumps", goal: "Cardio", equipment: "Bodyweight", difficulty: "Hard", caption: "15 frog jumps" },
  { name: "Star Jumps", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "20 star jumps" },
  { name: "Squat Pulses", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "20 squat pulses" },
  { name: "Lunge Pulses", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "15 lunge pulses each leg" },
  { name: "Single Leg Glute Bridge", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "10 single leg bridges each" },
  { name: "Donkey Kicks", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "15 donkey kicks each leg" },
  { name: "Fire Hydrants", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "15 fire hydrants each leg" },
  { name: "Dead Bug", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "10 dead bugs each side" },
  { name: "Bird Dog", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "10 bird dogs each side" },
  { name: "Hollow Body Hold", goal: "Abs", equipment: "Bodyweight", difficulty: "Hard", caption: "30 sec hollow hold" },
  { name: "V-Ups", goal: "Abs", equipment: "Bodyweight", difficulty: "Hard", caption: "15 v-ups" },
  { name: "Leg Raises", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "15 leg raises" },
  { name: "Reverse Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "15 reverse crunches" },
  { name: "Plank Up-Downs", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "10 plank up-downs" },
  { name: "Plank Jacks", goal: "Cardio", equipment: "Bodyweight", difficulty: "Hard", caption: "20 plank jacks" },
  { name: "Commando Crawl", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "10 steps commando crawl" },
  { name: "Inch Worms", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", caption: "10 inch worms" },
  { name: "Skater Hops", goal: "Cardio", equipment: "Bodyweight", difficulty: "Medium", caption: "️ 20 skater hops" },
  { name: "Lateral Bounds", goal: "Cardio", equipment: "Bodyweight", difficulty: "Hard", caption: "️ 10 lateral bounds each side" },
  { name: "Single Leg Deadlift", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "8 single leg deadlifts each" },
  { name: "Pistol Squats", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "5 pistol squats each leg" },
  { name: "Archer Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "5 archer push-ups each side" },
  { name: "Diamond Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "10 diamond push-ups" },
  { name: "Wide Grip Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "12 wide grip push-ups" },
  { name: "Decline Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "10 decline push-ups" },
  { name: "Hindu Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "️ 8 hindu push-ups" },
  { name: "Dive Bomber Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "️ 8 dive bomber push-ups" },
  { name: "Spiderman Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "️ 10 spiderman push-ups" },
  { name: "T Push-Ups", goal: "Full Body", equipment: "Bodyweight", difficulty: "Hard", caption: "8 T push-ups" },
  { name: "Clap Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "5 clap push-ups" },
  { name: "Single Arm Push-Ups", goal: "Strength", equipment: "Bodyweight", difficulty: "Hard", caption: "3 single arm push-ups each" },
  { name: "Handstand Push-Ups", goal: "Strength", equipment: "Wall", difficulty: "Hard", caption: "5 handstand push-ups" },
  { name: "Wall Sit Pulses", goal: "Strength", equipment: "Wall", difficulty: "Medium", caption: "20 wall sit pulses" },
  { name: "Wall Angels", goal: "Strength", equipment: "Wall", difficulty: "Easy", caption: "15 wall angels" },
  { name: "Butt Kickers", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec butt kickers" },
  { name: "Arm Circles", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "20 arm circles each direction" },
  { name: "Leg Swings", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "15 leg swings each leg" },
  { name: "Hip Circles", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "10 hip circles each direction" },
  { name: "Ankle Rolls", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "10 ankle rolls each foot" },
  { name: "Neck Rolls", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "5 neck rolls each direction" },
  { name: "Shoulder Shrugs", goal: "Strength", equipment: "Bodyweight", difficulty: "Easy", caption: "15 shoulder shrugs" },
  { name: "Torso Twists", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "️ 20 torso twists" },
  { name: "Standing Knee Raises", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "15 knee raises each leg" },
  { name: "Standing Oblique Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "15 oblique crunches each side" },
  { name: "Marching in Place", goal: "Cardio", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec marching" },
  { name: "Toe Touches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "15 toe touches" },
  { name: "Heel Touches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "20 heel touches" },
  { name: "Cross Body Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Medium", caption: "15 cross body crunches each side" },
  { name: "Sit-Ups", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "20 sit-ups" },
  { name: "Crunches", goal: "Abs", equipment: "Bodyweight", difficulty: "Easy", caption: "25 crunches" },
  { name: "Reverse Plank", goal: "Strength", equipment: "Bodyweight", difficulty: "Medium", caption: "30 sec reverse plank" },
  { name: "Side Plank Rotations", goal: "Abs", equipment: "Bodyweight", difficulty: "Hard", caption: "10 side plank rotations each side" },
  { name: "Plank to Downward Dog", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", caption: "10 plank to downward dog" },
  { name: "Downward Dog", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec downward dog" },
  { name: "Cobra Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec cobra stretch" },
  { name: "Child's Pose", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec child's pose" },
  { name: "Cat Cow Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "10 cat cow stretches" },
  { name: "Thread the Needle", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "🪡 10 thread the needle each side" },
  { name: "World's Greatest Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Medium", caption: "5 world's greatest stretch each side" },
  { name: "90/90 Hip Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec 90/90 hip stretch" },
  { name: "Pigeon Pose", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec pigeon pose each side" },
  { name: "Figure 4 Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec figure 4 stretch each side" },
  { name: "Seated Spinal Twist", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "️ 30 sec spinal twist each side" },
  { name: "Seated Forward Fold", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec forward fold" },
  { name: "Standing Forward Fold", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec standing forward fold" },
  { name: "Standing Quad Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec quad stretch each leg" },
  { name: "Standing Calf Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec calf stretch each leg" },
  { name: "Standing Hamstring Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec hamstring stretch each leg" },
  { name: "Arm Crossovers", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "15 arm crossovers" },
  { name: "Tricep Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec tricep stretch each arm" },
  { name: "Shoulder Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec shoulder stretch each arm" },
  { name: "Chest Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec chest stretch" },
  { name: "Hip Flexor Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec hip flexor stretch each leg" },
  { name: "IT Band Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec IT band stretch each leg" },
  { name: "Glute Stretch", goal: "Full Body", equipment: "Bodyweight", difficulty: "Easy", caption: "30 sec glute stretch each leg" },
  
  // Dumbbell Exercises
  { name: "Dumbbell Squat", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "️ 15 dumbbell squats" },
  { name: "Goblet Squat", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 goblet squats" },
  { name: "Dumbbell Lunge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 dumbbell lunges each leg" },
  { name: "Dumbbell Step-Ups", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 dumbbell step-ups each leg" },
  { name: "Dumbbell Romanian Deadlift", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 Romanian deadlifts" },
  { name: "Dumbbell Sumo Deadlift", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 sumo deadlifts" },
  { name: "Dumbbell Bench Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 dumbbell bench press" },
  { name: "Dumbbell Incline Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "10 incline press" },
  { name: "Dumbbell Decline Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "10 decline press" },
  { name: "Dumbbell Flyes", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 dumbbell flyes" },
  { name: "Dumbbell Pullover", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 dumbbell pullovers" },
  { name: "Bent Over Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 bent over rows" },
  { name: "Single Arm Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 single arm rows each" },
  { name: "Upright Row", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 upright rows" },
  { name: "Reverse Fly", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 reverse flyes" },
  { name: "Lateral Raise", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "️ 15 lateral raises" },
  { name: "Front Raise", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 front raises" },
  { name: "Rear Delt Fly", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 rear delt flyes" },
  { name: "Arnold Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "10 Arnold presses" },
  { name: "Push Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "10 push presses" },
  { name: "Dumbbell Snatch", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "8 dumbbell snatches each arm" },
  { name: "Dumbbell Clean", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "8 dumbbell cleans each arm" },
  { name: "Dumbbell Thruster", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "10 dumbbell thrusters" },
  { name: "Man Makers", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "5 man makers" },
  { name: "Dumbbell Burpee", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "8 dumbbell burpees" },
  { name: "Renegade Rows", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "10 renegade rows" },
  { name: "Dumbbell Mountain Climbers", goal: "Cardio", equipment: "Dumbbells", difficulty: "Hard", caption: "️ 20 dumbbell mountain climbers" },
  { name: "Bicep Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 bicep curls" },
  { name: "Hammer Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 hammer curls" },
  { name: "Concentration Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 concentration curls each arm" },
  { name: "21s Bicep Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "21s bicep curls" },
  { name: "Zottman Curls", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 Zottman curls" },
  { name: "Overhead Tricep Extension", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 overhead tricep extensions" },
  { name: "Lying Tricep Extension", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 lying tricep extensions" },
  { name: "Tricep Kickbacks", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 tricep kickbacks" },
  { name: "Close Grip Press", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 close grip press" },
  { name: "Dumbbell Shrugs", goal: "Strength", equipment: "Dumbbells", difficulty: "Easy", caption: "15 dumbbell shrugs" },
  { name: "Farmer's Walk", goal: "Full Body", equipment: "Dumbbells", difficulty: "Medium", caption: "30 sec farmer's walk" },
  { name: "Suitcase Carry", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", caption: "20 steps suitcase carry each side" },
  { name: "Overhead Carry", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "20 steps overhead carry" },
  { name: "Dumbbell Swing", goal: "Cardio", equipment: "Dumbbells", difficulty: "Medium", caption: "20 dumbbell swings" },
  { name: "Single Arm Swing", goal: "Cardio", equipment: "Dumbbells", difficulty: "Medium", caption: "15 single arm swings each" },
  { name: "Dumbbell High Pull", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "10 dumbbell high pulls" },
  { name: "Dumbbell Windmill", goal: "Abs", equipment: "Dumbbells", difficulty: "Hard", caption: "️ 8 windmills each side" },
  { name: "Turkish Get-Up", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "3 Turkish get-ups each side" },
  { name: "Dumbbell Crawl", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "10 steps dumbbell crawl" },
  { name: "Weighted Sit-Ups", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", caption: "15 weighted sit-ups" },
  { name: "Weighted Crunches", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", caption: "20 weighted crunches" },
  { name: "Weighted Russian Twists", goal: "Abs", equipment: "Dumbbells", difficulty: "Medium", caption: "20 weighted Russian twists" },
  { name: "Weighted Plank", goal: "Abs", equipment: "Dumbbells", difficulty: "Hard", caption: "30 sec weighted plank" },
  { name: "Weighted Glute Bridge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "15 weighted glute bridges" },
  { name: "Single Leg Hip Thrust", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "10 single leg hip thrusts each" },
  { name: "Weighted Hip Thrust", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "15 weighted hip thrusts" },
  { name: "Bulgarian Split Squat", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "10 Bulgarian split squats each leg" },
  { name: "Reverse Lunge to Knee Drive", goal: "Cardio", equipment: "Dumbbells", difficulty: "Medium", caption: "12 reverse lunge to knee drive each leg" },
  { name: "Lateral Lunge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "️ 12 lateral lunges each leg" },
  { name: "Curtsy Lunge", goal: "Strength", equipment: "Dumbbells", difficulty: "Medium", caption: "12 curtsy lunges each leg" },
  { name: "Walking Lunge", goal: "Cardio", equipment: "Dumbbells", difficulty: "Medium", caption: "20 walking lunges" },
  { name: "Reverse Fly to External Rotation", goal: "Strength", equipment: "Dumbbells", difficulty: "Hard", caption: "10 reverse fly to external rotation" },
  { name: "Dumbbell Complex", goal: "Full Body", equipment: "Dumbbells", difficulty: "Hard", caption: "5 dumbbell complexes" },
  { name: "Dumbbell Ladder", goal: "Cardio", equipment: "Dumbbells", difficulty: "Hard", caption: "1-10 dumbbell ladder" },
  { name: "Dumbbell Tabata", goal: "Cardio", equipment: "Dumbbells", difficulty: "Hard", caption: "4 min dumbbell tabata" },
  { name: "Dumbbell EMOM", goal: "Cardio", equipment: "Dumbbells", difficulty: "Hard", caption: "5 min dumbbell EMOM" },
  { name: "Dumbbell Circuit", goal: "Full Body", equipment: "Dumbbells", difficulty: "Medium", caption: "3 rounds dumbbell circuit" },
  
  // Full Gym Exercises
  { name: "Barbell Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "️ 12 barbell squats" },
  { name: "Front Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "️ 10 front squats" },
  { name: "Overhead Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "8 overhead squats" },
  { name: "Barbell Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 barbell deadlifts" },
  { name: "Sumo Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 sumo deadlifts" },
  { name: "Romanian Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 Romanian deadlifts" },
  { name: "Stiff Leg Deadlift", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 stiff leg deadlifts" },
  { name: "Barbell Row", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 barbell rows" },
  { name: "Pendlay Row", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "10 Pendlay rows" },
  { name: "T-Bar Row", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 T-bar rows" },
  { name: "Barbell Bench Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 barbell bench press" },
  { name: "Incline Barbell Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 incline barbell press" },
  { name: "Decline Barbell Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 decline barbell press" },
  { name: "Overhead Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 overhead press" },
  { name: "Push Press", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "8 push press" },
  { name: "Push Jerk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "6 push jerks" },
  { name: "Split Jerk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "6 split jerks" },
  { name: "Clean and Jerk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "5 clean and jerks" },
  { name: "Power Clean", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "6 power cleans" },
  { name: "Hang Clean", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "6 hang cleans" },
  { name: "Snatch", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "5 snatches" },
  { name: "Power Snatch", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "6 power snatches" },
  { name: "Hang Snatch", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "6 hang snatches" },
  { name: "Thruster", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "10 thrusters" },
  { name: "Barbell Curl", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 barbell curls" },
  { name: "Close Grip Bench Press", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 close grip bench press" },
  { name: "Skull Crushers", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 skull crushers" },
  { name: "Barbell Shrugs", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 barbell shrugs" },
  { name: "Upright Row", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 upright rows" },
  { name: "Face Pulls", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 face pulls" },
  { name: "Cable Crossover", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 cable crossovers" },
  { name: "Cable Fly", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 cable flyes" },
  { name: "Lat Pulldown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "⬇️ 12 lat pulldowns" },
  { name: "Wide Grip Pulldown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "️ 12 wide grip pulldowns" },
  { name: "Close Grip Pulldown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 close grip pulldowns" },
  { name: "Seated Cable Row", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 seated cable rows" },
  { name: "Cable Bicep Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 cable bicep curls" },
  { name: "Cable Hammer Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 cable hammer curls" },
  { name: "Cable Tricep Pushdown", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "⬇️ 15 cable tricep pushdowns" },
  { name: "Overhead Cable Extension", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 overhead cable extensions" },
  { name: "Cable Lateral Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "️ 15 cable lateral raises" },
  { name: "Cable Rear Delt Fly", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 cable rear delt flyes" },
  { name: "Cable Wood Chops", goal: "Abs", equipment: "Full Gym", difficulty: "Medium", caption: "🪓 12 cable wood chops each side" },
  { name: "Cable Russian Twists", goal: "Abs", equipment: "Full Gym", difficulty: "Medium", caption: "20 cable Russian twists" },
  { name: "Cable Crunches", goal: "Abs", equipment: "Full Gym", difficulty: "Medium", caption: "15 cable crunches" },
  { name: "Hanging Knee Raises", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", caption: "12 hanging knee raises" },
  { name: "Hanging Leg Raises", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", caption: "10 hanging leg raises" },
  { name: "Toes to Bar", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", caption: "8 toes to bar" },
  { name: "L-Sit", goal: "Abs", equipment: "Full Gym", difficulty: "Hard", caption: "20 sec L-sit" },
  { name: "Pull-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "8 pull-ups" },
  { name: "Chin-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "8 chin-ups" },
  { name: "Wide Grip Pull-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "️ 6 wide grip pull-ups" },
  { name: "Commando Pull-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "5 commando pull-ups" },
  { name: "Muscle-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "3 muscle-ups" },
  { name: "Dips", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "⬇️ 10 dips" },
  { name: "Weighted Dips", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "⬇️ 8 weighted dips" },
  { name: "Ring Dips", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "6 ring dips" },
  { name: "Ring Push-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "8 ring push-ups" },
  { name: "Ring Rows", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "10 ring rows" },
  { name: "Ring Muscle-Ups", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "2 ring muscle-ups" },
  { name: "Leg Press", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 leg press" },
  { name: "Hack Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "️ 12 hack squats" },
  { name: "Leg Extension", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 leg extensions" },
  { name: "Leg Curl", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 leg curls" },
  { name: "Calf Press", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "20 calf press" },
  { name: "Standing Calf Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "20 standing calf raises" },
  { name: "Seated Calf Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "20 seated calf raises" },
  { name: "Hip Abduction", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 hip abductions" },
  { name: "Hip Adduction", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "15 hip adductions" },
  { name: "Chest Press Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 chest press machine" },
  { name: "Shoulder Press Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "️ 12 shoulder press machine" },
  { name: "Lat Pulldown Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "⬇️ 12 lat pulldown machine" },
  { name: "Row Machine", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 row machine" },
  { name: "Pec Deck", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 pec deck" },
  { name: "Reverse Pec Deck", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 reverse pec deck" },
  { name: "Preacher Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 preacher curls" },
  { name: "Cable Preacher Curls", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "12 cable preacher curls" },
  { name: "Smith Machine Squat", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "️ 12 Smith machine squats" },
  { name: "Smith Machine Bench", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "10 Smith machine bench" },
  { name: "Smith Machine Row", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "12 Smith machine rows" },
  { name: "Smith Machine Calf Raise", goal: "Strength", equipment: "Full Gym", difficulty: "Easy", caption: "20 Smith machine calf raises" },
  { name: "Treadmill Sprint", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "30 sec treadmill sprint" },
  { name: "Treadmill Incline Walk", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "2 min incline walk" },
  { name: "Stationary Bike", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "2 min stationary bike" },
  { name: "Elliptical", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "2 min elliptical" },
  { name: "Rowing Machine", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "500m rowing machine" },
  { name: "Stair Climber", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "2 min stair climber" },
  { name: "Battle Ropes", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "🪢 30 sec battle ropes" },
  { name: "Tire Flips", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "10 tire flips" },
  { name: "Sledgehammer Swings", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 sledgehammer swings" },
  { name: "Prowler Push", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yard prowler push" },
  { name: "Sled Pull", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yard sled pull" },
  { name: "Atlas Stone Lift", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "5 atlas stone lifts" },
  { name: "Sandbag Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "30 sec sandbag carry" },
  { name: "Medicine Ball Slam", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "15 medicine ball slams" },
  { name: "Medicine Ball Throw", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "10 medicine ball throws" },
  { name: "Wall Ball", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "15 wall balls" },
  { name: "Box Step-Ups", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "20 box step-ups" },
  { name: "Box Jump Overs", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "10 box jump overs" },
  { name: "Lateral Box Jumps", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "10 lateral box jumps each side" },
  { name: "Depth Jumps", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "8 depth jumps" },
  { name: "Broad Jumps", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "️ 10 broad jumps" },
  { name: "Vertical Jumps", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "15 vertical jumps" },
  { name: "Single Leg Box Jumps", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "5 single leg box jumps each" },
  { name: "Agility Ladder", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "30 sec agility ladder" },
  { name: "Cone Drills", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "30 sec cone drills" },
  { name: "Shuttle Runs", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "5 shuttle runs" },
  { name: "Sprint Intervals", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "8x20 yard sprints" },
  { name: "Parachute Runs", goal: "Cardio", equipment: "Full Gym", difficulty: "Hard", caption: "30 sec parachute runs" },
  { name: "Resistance Band Runs", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "30 sec resistance band runs" },
  { name: "Bounding", goal: "Cardio", equipment: "Full Gym", difficulty: "Medium", caption: "20 bounds" },
  { name: "High Skips", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "30 sec high skips" },
  { name: "Carioca", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "20 yards carioca each direction" },
  { name: "Backpedal", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "20 yards backpedal" },
  { name: "Side Shuffle", goal: "Cardio", equipment: "Full Gym", difficulty: "Easy", caption: "️20 yards side shuffle each direction" },
  { name: "Bear Crawl Forward", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards bear crawl forward" },
  { name: "Bear Crawl Backward", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards bear crawl backward" },
  { name: "Crab Walk Forward", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards crab walk forward" },
  { name: "Crab Walk Backward", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards crab walk backward" },
  { name: "Duck Walk", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards duck walk" },
  { name: "Lizard Crawl", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards lizard crawl" },
  { name: "Army Crawl", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards army crawl" },
  { name: "Spiderman Crawl", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "️ 20 yards spiderman crawl" },
  { name: "Gorilla Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards gorilla walk" },
  { name: "Frog Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards frog walk" },
  { name: "Seal Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards seal walk" },
  { name: "Inchworm Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards inchworm walk" },
  { name: "Wheelbarrow Walk", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards wheelbarrow walk" },
  { name: "Partner Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards partner carry" },
  { name: "Fireman Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards fireman carry" },
  { name: "Piggyback Carry", goal: "Full Body", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards piggyback carry" },
  { name: "Overhead Plate Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards overhead plate carry" },
  { name: "Front Loaded Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards front loaded carry" },
  { name: "Zercher Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards Zercher carry" },
  { name: "Yoke Walk", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards yoke walk" },
  { name: "Frame Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "️ 20 yards frame carry" },
  { name: "Log Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards log carry" },
  { name: "Keg Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards keg carry" },
  { name: "Stone Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards stone carry" },
  { name: "Bucket Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards bucket carry" },
  { name: "Water Jug Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Medium", caption: "20 yards water jug carry" },
  { name: "Odd Object Carry", goal: "Strength", equipment: "Full Gym", difficulty: "Hard", caption: "20 yards odd object carry" }
];

export const fitnessGoals = ["Abs", "Strength", "Cardio", "Full Body", "Quick Workout"];
export const timeOptions = ["5", "10", "15", "20", "25", "30"];
export const equipmentOptions = ["Bodyweight", "Dumbbells", "Full Gym"];